import { useEffect, useState } from 'react'
import { getSession } from '../auth'
import { API_URL } from '../api'
import './FleetOperations.css'

async function api(path, token, init = {}) {
  const response = await fetch(`${API_URL}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', ...init.headers } })
  const body = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(body.message || body.error || 'Request failed')
  return body
}

export default function FleetOperations() {
  const token = getSession()?.token
  const [drivers, setDrivers] = useState([]); const [trips, setTrips] = useState([]); const [vehicles, setVehicles] = useState([])
  const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false)
  const [driver, setDriver] = useState({ name: '', licenseNumber: '', cdlClass: '', coiExpiry: '', employmentStatus: 'ACTIVE', contact: '' })
  const [trip, setTrip] = useState({ vehicleId: '', driverId: '', startOdometer: '', fuelStart: '', chargeStart: '' })
  const [vehicle, setVehicle] = useState({ registration: '', make: '', model: '', year: '', fuelType: '', ownershipStatus: '', branch: '', status: 'AVAILABLE', odometerCurrent: '0' })
  const refresh = async () => { setLoading(true); try { const [d, t, v] = await Promise.all([api('/api/drivers', token), api('/api/trips', token), api('/api/vehicles', token)]); setDrivers(d.drivers || []); setTrips(t.trips || []); setVehicles(v.vehicles || []) } catch (e) { setMessage(e.message) } finally { setLoading(false) } }
  useEffect(() => { refresh() }, [])
  const save = async (event, path, data, reset) => { event.preventDefault(); setLoading(true); try { await api(path, token, { method: 'POST', body: JSON.stringify(data) }); reset(); await refresh(); setMessage('Saved successfully.') } catch (e) { setMessage(e.message) } finally { setLoading(false) } }
  const updateStatus = async (id, status) => { try { await api(`/api/vehicles/${id}/status`, token, { method: 'PATCH', body: JSON.stringify({ status }) }); await refresh(); setMessage('Vehicle status updated.') } catch (e) { setMessage(e.message) } }
  const tripAction = async (id, action) => { const end = action === 'end'; const reading = window.prompt(end ? 'End odometer reading' : 'Start odometer reading'); if (reading === null) return; try { await api(`/api/trips/${id}/${action}`, token, { method: 'POST', body: JSON.stringify(end ? { endOdometer: Number(reading) } : { startOdometer: Number(reading) }) }); await refresh(); setMessage(`Trip ${action}ed.`) } catch (e) { setMessage(e.message) } }
  return <section className="operations"><div className="operations-head"><div><h2>Drivers & trips</h2><p>Manage operational assignments and live fleet status.</p></div><button onClick={refresh} disabled={loading}>Refresh</button></div>{message && <p className="operations-message">{message}</p>}<div className="operations-grid">
    <article><h3>Add driver</h3><form onSubmit={e => save(e, '/api/drivers', driver, () => setDriver({ name: '', licenseNumber: '', cdlClass: '', coiExpiry: '', employmentStatus: 'ACTIVE', contact: '' }))}><input required placeholder="Driver name" value={driver.name} onChange={e => setDriver({ ...driver, name: e.target.value })}/><input required placeholder="Licence number" value={driver.licenseNumber} onChange={e => setDriver({ ...driver, licenseNumber: e.target.value })}/><input placeholder="Licence class" value={driver.cdlClass} onChange={e => setDriver({ ...driver, cdlClass: e.target.value })}/><input type="date" value={driver.coiExpiry} onChange={e => setDriver({ ...driver, coiExpiry: e.target.value })}/><select value={driver.employmentStatus} onChange={e => setDriver({ ...driver, employmentStatus: e.target.value })}><option>ACTIVE</option><option>INACTIVE</option><option>SUSPENDED</option></select><input placeholder="Contact" value={driver.contact} onChange={e => setDriver({ ...driver, contact: e.target.value })}/><button disabled={loading}>Add driver</button></form></article>
    <article><h3>Create trip</h3><form onSubmit={e => save(e, '/api/trips', { ...trip, startOdometer: trip.startOdometer ? Number(trip.startOdometer) : undefined }, () => setTrip({ vehicleId: '', driverId: '', startOdometer: '', fuelStart: '', chargeStart: '' }))}><select required value={trip.vehicleId} onChange={e => setTrip({ ...trip, vehicleId: e.target.value })}><option value="">Vehicle</option>{vehicles.map(v => <option key={v.id} value={v.id}>{v.registration}</option>)}</select><select value={trip.driverId} onChange={e => setTrip({ ...trip, driverId: e.target.value })}><option value="">Unassigned driver</option>{drivers.filter(d => d.employmentStatus === 'ACTIVE').map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select><input type="number" min="0" placeholder="Start odometer" value={trip.startOdometer} onChange={e => setTrip({ ...trip, startOdometer: e.target.value })}/><input type="number" min="0" step="0.01" placeholder="Fuel start" value={trip.fuelStart} onChange={e => setTrip({ ...trip, fuelStart: e.target.value })}/><input type="number" min="0" step="0.01" placeholder="Charge start" value={trip.chargeStart} onChange={e => setTrip({ ...trip, chargeStart: e.target.value })}/><button disabled={loading}>Create trip</button></form></article>
    <article><h3>Add vehicle</h3><form onSubmit={e => save(e, '/api/vehicles', { ...vehicle, year: vehicle.year ? Number(vehicle.year) : undefined, odometerCurrent: Number(vehicle.odometerCurrent) }, () => setVehicle({ registration: '', make: '', model: '', year: '', fuelType: '', ownershipStatus: '', branch: '', status: 'AVAILABLE', odometerCurrent: '0' }))}><input required placeholder="Registration" value={vehicle.registration} onChange={e => setVehicle({ ...vehicle, registration: e.target.value })}/><input placeholder="Make" value={vehicle.make} onChange={e => setVehicle({ ...vehicle, make: e.target.value })}/><input placeholder="Model" value={vehicle.model} onChange={e => setVehicle({ ...vehicle, model: e.target.value })}/><input type="number" placeholder="Year" value={vehicle.year} onChange={e => setVehicle({ ...vehicle, year: e.target.value })}/><input placeholder="Fuel type" value={vehicle.fuelType} onChange={e => setVehicle({ ...vehicle, fuelType: e.target.value })}/><input placeholder="Ownership status" value={vehicle.ownershipStatus} onChange={e => setVehicle({ ...vehicle, ownershipStatus: e.target.value })}/><input placeholder="Branch" value={vehicle.branch} onChange={e => setVehicle({ ...vehicle, branch: e.target.value })}/><button disabled={loading}>Add vehicle</button></form></article>
  </div><div className="operations-table"><h3>Driver register</h3><table><thead><tr><th>Driver</th><th>Licence</th><th>Class</th><th>Expiry</th><th>Status</th><th>Trips</th></tr></thead><tbody>{drivers.map(d => <tr key={d.id}><td>{d.name}</td><td>{d.licenseNumber}</td><td>{d.cdlClass || '—'}</td><td>{d.coiExpiry ? new Date(d.coiExpiry).toLocaleDateString() : '—'}</td><td>{d.employmentStatus}</td><td>{d._count?.trips || 0}</td></tr>)}</tbody></table></div><div className="operations-table"><h3>Trips</h3><table><thead><tr><th>Vehicle</th><th>Driver</th><th>Status</th><th>Distance</th><th>Action</th></tr></thead><tbody>{trips.map(t => <tr key={t.id}><td>{t.vehicle?.registration}</td><td>{t.driver?.name || 'Unassigned'}</td><td>{t.status}</td><td>{t.distanceDriven ?? '—'} km</td><td>{t.status === 'PLANNED' && <button onClick={() => tripAction(t.id, 'start')}>Start</button>}{t.status === 'ONGOING' && <button onClick={() => tripAction(t.id, 'end')}>End</button>}</td></tr>)}</tbody></table></div><div className="operations-table"><h3>Vehicle operations</h3><table><thead><tr><th>Vehicle</th><th>Year</th><th>Fuel</th><th>Branch</th><th>Status</th></tr></thead><tbody>{vehicles.map(v => <tr key={v.id}><td>{v.registration}</td><td>{v.year || '—'}</td><td>{v.fuelType || '—'}</td><td>{v.branch || '—'}</td><td><select value={v.status} onChange={e => updateStatus(v.id, e.target.value)}><option>AVAILABLE</option><option>RESERVED</option><option>ON_TRIP</option><option>IN_MAINTENANCE</option><option>OUT_OF_SERVICE</option></select></td></tr>)}</tbody></table></div></section>
}
