import { useEffect, useMemo, useState } from 'react'
import { clearSession, getSession } from '../auth'
import './OperationsPortal.css'

const API_URL = import.meta.env.VITE_FLEETLINK_API_URL || 'http://localhost:3000'

async function request(path, token, init = {}) {
  const response = await fetch(`${API_URL}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, ...(init.body ? { 'Content-Type': 'application/json' } : {}), ...init.headers } })
  const data = await response.json().catch(() => ({ message: response.statusText }))
  if (!response.ok) throw new Error(data.message || data.error || 'FleetLink request failed')
  return data
}

function OperationsPortal() {
  const session = getSession()
  const token = session?.token || ''
  const role = session?.user?.role || ''
  const [active, setActive] = useState('overview')
  const [vehicles, setVehicles] = useState([])
  const [bookings, setBookings] = useState([])
  const [status, setStatus] = useState('Loading your FleetLink workspace…')
  const [loading, setLoading] = useState(false)
  const [availability, setAvailability] = useState({ start: '', end: '' })
  const [availableVehicles, setAvailableVehicles] = useState([])
  const [booking, setBooking] = useState({ vehicleId: '', start: '', end: '', passengerCount: '1', justification: '', destination: '', serviceType: 'SELF_DRIVE', pickupLocation: '', guestName: '', guestContact: '' })
  const [customer, setCustomer] = useState({ name: '', email: '', driverLicense: '', contact: '' })
  const [rental, setRental] = useState({ vehicleId: '', customerId: '', start: '', end: '', agreedRate: '', depositAmount: '', depositPaid: false })
  const [inspection, setInspection] = useState({ reservationId: '', type: 'checkout', odometerReading: '', fuelLevel: '', conditionNotes: '', conditionPhotos: '' })
  const isDepartmentHead = role === 'DEPARTMENT_HEAD'
  const items = useMemo(() => [['overview', 'Overview'], ['availability', 'Vehicle availability'], ['bookings', isDepartmentHead ? 'Booking approvals' : 'My booking requests'], ['customers', 'Register rental customer'], ['rentals', 'Rental reservations'], ['inspections', 'Rental inspections']], [isDepartmentHead])

  async function refresh() {
    setLoading(true)
    try {
      const [fleet, bookingData] = await Promise.all([fetch(`${API_URL}/api/public/vehicles`).then(r => r.json()), request('/api/bookings?limit=100', token)])
      setVehicles(fleet.vehicles || []); setBookings(bookingData.bookings || []); setStatus('Your workspace is up to date.')
    } catch (error) { setStatus(error.message) } finally { setLoading(false) }
  }
  useEffect(() => { refresh() }, [])

  async function searchAvailability(event) { event.preventDefault(); setLoading(true); try { const data = await request(`/api/vehicles/available?start=${encodeURIComponent(new Date(availability.start).toISOString())}&end=${encodeURIComponent(new Date(availability.end).toISOString())}`, token); setAvailableVehicles(data.vehicles || []); setStatus('Available vehicles loaded.') } catch (error) { setStatus(error.message) } finally { setLoading(false) } }
  async function saveBooking(event) { event.preventDefault(); setLoading(true); try { await request('/api/bookings', token, { method: 'POST', body: JSON.stringify({ ...booking, start: new Date(booking.start).toISOString(), end: new Date(booking.end).toISOString(), passengerCount: Number(booking.passengerCount), kind: 'CORPORATE' }) }); setBooking({ vehicleId: '', start: '', end: '', passengerCount: '1', justification: '', destination: '', serviceType: 'SELF_DRIVE', pickupLocation: '', guestName: '', guestContact: '' }); await refresh(); setStatus('Booking request submitted.') } catch (error) { setStatus(error.message) } finally { setLoading(false) } }
  async function decideBooking(item, action) { const comment = action === 'rejection' ? window.prompt('Reason for rejection:') : ''; if (action === 'rejection' && !comment?.trim()) return; setLoading(true); try { await request(`/api/bookings/${item.id}/${action}`, token, { method: 'POST', ...(comment ? { body: JSON.stringify({ comment }) } : {}) }); await refresh(); setStatus(`Booking ${action === 'approval' ? 'approved' : 'rejected'}.`) } catch (error) { setStatus(error.message) } finally { setLoading(false) } }
  async function saveCustomer(event) { event.preventDefault(); setLoading(true); try { const data = await request('/api/customers', token, { method: 'POST', body: JSON.stringify(customer) }); setCustomer({ name: '', email: '', driverLicense: '', contact: '' }); setRental(value => ({ ...value, customerId: data.customer?.id || value.customerId })); setStatus('Rental customer registered.') } catch (error) { setStatus(error.message) } finally { setLoading(false) } }
  async function saveRental(event) { event.preventDefault(); setLoading(true); try { const data = await request('/api/rental-reservations', token, { method: 'POST', body: JSON.stringify({ ...rental, start: new Date(rental.start).toISOString(), end: new Date(rental.end).toISOString() }) }); setInspection(value => ({ ...value, reservationId: data.reservation?.id || value.reservationId })); setStatus(`Rental reservation created${data.reservation?.id ? `. ID: ${data.reservation.id}` : ''}`) } catch (error) { setStatus(error.message) } finally { setLoading(false) } }
  async function extendRental(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const reservationId = form.get('reservationId'); const newEnd = form.get('newEnd'); setLoading(true); try { await request(`/api/rental-reservations/${reservationId}/extend`, token, { method: 'POST', body: JSON.stringify({ newEnd: new Date(newEnd).toISOString() }) }); setStatus('Rental return time extended.') } catch (error) { setStatus(error.message) } finally { setLoading(false) } }
  async function saveInspection(event) { event.preventDefault(); setLoading(true); try { const payload = { odometerReading: inspection.odometerReading, conditionNotes: inspection.conditionNotes, conditionPhotos: inspection.conditionPhotos.split(',').map(url => url.trim()).filter(Boolean) }; if (inspection.fuelLevel) payload.fuelLevel = inspection.fuelLevel; await request(`/api/rental-reservations/${inspection.reservationId}/inspections/${inspection.type}`, token, { method: 'POST', body: JSON.stringify(payload) }); setStatus(`${inspection.type === 'checkout' ? 'Checkout' : 'Check-in'} inspection saved.`) } catch (error) { setStatus(error.message) } finally { setLoading(false) } }

  return <main className="operations-shell"><aside className="operations-sidebar"><a href="/" className="operations-brand">Fleet<span>Link</span><small>OPERATIONS PORTAL</small></a><nav>{items.map(([key, label]) => <button key={key} className={active === key ? 'is-active' : ''} onClick={() => setActive(key)}>{label}</button>)}</nav><div className="operations-user"><b>{session?.user?.name || 'User'}</b><small>{role.replace(/_/g, ' ')}</small><button onClick={() => { clearSession(); window.location.assign('/login') }}>Sign out</button></div></aside><section className="operations-content"><header><p>FleetLink / Operations</p><h1>{items.find(([key]) => key === active)?.[1]}</h1><button onClick={refresh} disabled={loading}>{loading ? 'Loading…' : 'Refresh'}</button></header><p className="operations-status">{status}</p>
    {active === 'overview' && <section className="operations-card"><h2>Welcome, {session?.user?.name || 'there'}.</h2><p>{isDepartmentHead ? 'Review the booking requests assigned to you, or complete rental operations.' : 'Request an available vehicle or complete rental operations.'}</p><div className="operations-stats"><span><b>{vehicles.length}</b> vehicles visible</span><span><b>{bookings.length}</b> {isDepartmentHead ? 'assigned requests' : 'your requests'}</span></div></section>}
    {active === 'availability' && <section className="operations-card"><h2>Find an available vehicle</h2><form onSubmit={searchAvailability}><label>Start<input type="datetime-local" value={availability.start} onChange={e => setAvailability({ ...availability, start: e.target.value })} required /></label><label>End<input type="datetime-local" value={availability.end} onChange={e => setAvailability({ ...availability, end: e.target.value })} required /></label><button disabled={loading}>Search</button></form><VehicleTable vehicles={availableVehicles} /></section>}
    {active === 'bookings' && <section className="operations-card"><h2>{isDepartmentHead ? 'Assigned booking requests' : 'Submit a booking request'}</h2>{!isDepartmentHead && <form onSubmit={saveBooking}><label>Service<select value={booking.serviceType} onChange={e => setBooking({ ...booking, serviceType: e.target.value })}><option value="SELF_DRIVE">Self-drive rental</option><option value="CHAUFFEURED_TRANSFER">Chauffeured transfer</option></select></label><label>Vehicle<select value={booking.vehicleId} onChange={e => setBooking({ ...booking, vehicleId: e.target.value })} required><option value="">Select vehicle</option>{vehicles.map(v => <option key={v.id} value={v.id}>{v.registration} — {v.make} {v.model}</option>)}</select></label><label>Start<input type="datetime-local" value={booking.start} onChange={e => setBooking({ ...booking, start: e.target.value })} required /></label><label>End<input type="datetime-local" value={booking.end} onChange={e => setBooking({ ...booking, end: e.target.value })} required /></label><label>Passengers<input type="number" min="1" value={booking.passengerCount} onChange={e => setBooking({ ...booking, passengerCount: e.target.value })} required /></label>{booking.serviceType === 'CHAUFFEURED_TRANSFER' && <><label className="wide">Pickup location<input value={booking.pickupLocation} onChange={e => setBooking({ ...booking, pickupLocation: e.target.value })} required /></label><label>Guest name<input value={booking.guestName} onChange={e => setBooking({ ...booking, guestName: e.target.value })} required /></label><label>Guest contact<input value={booking.guestContact} onChange={e => setBooking({ ...booking, guestContact: e.target.value })} required /></label></>}<label className="wide">Destination<input value={booking.destination} onChange={e => setBooking({ ...booking, destination: e.target.value })} required /></label><label className="wide">Purpose<input value={booking.justification} onChange={e => setBooking({ ...booking, justification: e.target.value })} required /></label><button disabled={loading}>Submit request</button></form>}<BookingTable bookings={bookings} canDecide={isDepartmentHead} onDecide={decideBooking} /></section>}
    {active === 'customers' && <section className="operations-card"><h2>Register rental customer</h2><form onSubmit={saveCustomer}><label>Name<input value={customer.name} onChange={e => setCustomer({ ...customer, name: e.target.value })} required /></label><label>Email<input type="email" value={customer.email} onChange={e => setCustomer({ ...customer, email: e.target.value })} required /></label><label>Driver licence<input value={customer.driverLicense} onChange={e => setCustomer({ ...customer, driverLicense: e.target.value })} required /></label><label>Contact<input value={customer.contact} onChange={e => setCustomer({ ...customer, contact: e.target.value })} /></label><button disabled={loading}>Register customer</button></form></section>}
    {active === 'rentals' && <section className="operations-card"><h2>Create or extend a rental</h2><form onSubmit={saveRental}><label>Vehicle<select value={rental.vehicleId} onChange={e => setRental({ ...rental, vehicleId: e.target.value })} required><option value="">Select vehicle</option>{vehicles.map(v => <option key={v.id} value={v.id}>{v.registration}</option>)}</select></label><label>Customer ID<input value={rental.customerId} onChange={e => setRental({ ...rental, customerId: e.target.value })} required /></label><label>Start<input type="datetime-local" value={rental.start} onChange={e => setRental({ ...rental, start: e.target.value })} required /></label><label>End<input type="datetime-local" value={rental.end} onChange={e => setRental({ ...rental, end: e.target.value })} required /></label><label>Rate<input type="number" min="0" value={rental.agreedRate} onChange={e => setRental({ ...rental, agreedRate: e.target.value })} required /></label><label>Deposit<input type="number" min="0" value={rental.depositAmount} onChange={e => setRental({ ...rental, depositAmount: e.target.value })} required /></label><button disabled={loading}>Create rental</button></form><hr /><form onSubmit={extendRental}><label>Reservation ID<input name="reservationId" required /></label><label>New return time<input name="newEnd" type="datetime-local" required /></label><button disabled={loading}>Extend rental</button></form></section>}
    {active === 'inspections' && <section className="operations-card"><h2>Record rental inspection</h2><form onSubmit={saveInspection}><label>Reservation ID<input value={inspection.reservationId} onChange={e => setInspection({ ...inspection, reservationId: e.target.value })} required /></label><label>Inspection<select value={inspection.type} onChange={e => setInspection({ ...inspection, type: e.target.value })}><option value="checkout">Checkout</option><option value="checkin">Check-in</option></select></label><label>Odometer<input type="number" min="0" value={inspection.odometerReading} onChange={e => setInspection({ ...inspection, odometerReading: e.target.value })} required /></label><label>Fuel / charge level<input type="number" min="0" step="0.01" value={inspection.fuelLevel} onChange={e => setInspection({ ...inspection, fuelLevel: e.target.value })} /></label><label className="wide">Condition notes<input value={inspection.conditionNotes} onChange={e => setInspection({ ...inspection, conditionNotes: e.target.value })} /></label><label className="wide">Photo URLs (comma-separated)<input value={inspection.conditionPhotos} onChange={e => setInspection({ ...inspection, conditionPhotos: e.target.value })} required={inspection.type === 'checkout'} /></label><button disabled={loading}>Save inspection</button></form></section>}
  </section></main>
}

function VehicleTable({ vehicles }) { return <div className="operations-table"><table><thead><tr><th>Registration</th><th>Vehicle</th></tr></thead><tbody>{vehicles.length ? vehicles.map(v => <tr key={v.id}><td>{v.registration}</td><td>{[v.make, v.model].filter(Boolean).join(' ')}</td></tr>) : <tr><td colSpan="2">No vehicles loaded yet.</td></tr>}</tbody></table></div> }
function BookingTable({ bookings, canDecide, onDecide }) { return <div className="operations-table"><table><thead><tr><th>Vehicle</th><th>Requester</th><th>Window</th><th>Status</th>{canDecide && <th>Action</th>}</tr></thead><tbody>{bookings.length ? bookings.map(b => <tr key={b.id}><td>{b.vehicle?.registration || '-'}</td><td>{b.requestedBy?.name || '-'}</td><td>{new Date(b.startAt).toLocaleString()}</td><td>{b.status}</td>{canDecide && <td>{b.status === 'PENDING' && <><button onClick={() => onDecide(b, 'approval')}>Approve</button><button className="reject" onClick={() => onDecide(b, 'rejection')}>Reject</button></>}</td>}</tr>) : <tr><td colSpan={canDecide ? 5 : 4}>No booking requests found.</td></tr>}</tbody></table></div> }

export default OperationsPortal
